@name=get_order_by_id
GET http://localhost:3000/orders/1


###
@name=create_order
POST http://localhost:3000/orders
Content-Type: application/json

{
  "orderId": 1,
  "customerId": 1,
  "items": [
    {
      "product": "Boné",
      "quantity": 2,
      "price": 10.90
    },
    {
      "product": "Lápis",
      "quantity": 1,
      "price": 3
    }
  ]
}